os: linux
jdk: oraclejdk8
dist: trusty
sudo: true # faster builds
group: stable
addons:
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server
      - mysql-client
language: java
services:
  - mysql
script:
  - ./scripts/travis.build.sh
